[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "fcetool"
version = "1.0.6"
description = "Extract specific files from remote ROM.ZIP archives without downloading the complete ROM"
requires-python = ">=3.8"

dependencies = [
    "aiohttp",
    "pyzstd",
]

authors = [
  {name = "offici5l"}
]


[project.urls]
Repository = "https://github.com/fcetool"

[project.scripts]
fcetool = "fcetool.cli:main"

[tool.setuptools.packages.find]
where = ["."]
